catalog/urls.py
from django.urls import path
from . import views

from catalog.views import home, contacts
from catalog.apps import CatalogConfig

app_name = CatalogConfig.name

urlpatterns = [
    path('', views.home, name='list'),
    path('contacts/<int:id>', views.contacts, name='details')
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace="catalog"))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

catalog/models.py
from django.db import models


NULLABLE = {'blank': True, 'null': True}


class Category(models.Model):
    name = models.CharField(max_length=200, verbose_name='Наименование')
    description = models.TextField(max_length=500, verbose_name='Описание')

    def __str__(self):
        return f'{self.name}'

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'


class Product(models.Model):
    name = models.CharField(max_length=200, verbose_name='Наименование')
    description = models.CharField(max_length=500, verbose_name='Описание')
    preview = models.ImageField(upload_to='home/', verbose_name='изображение (превью)', **NULLABLE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name='Категория')
    price = models.IntegerField(verbose_name='Цена за покупку')
    created = models.DateTimeField(auto_now=True, verbose_name='Дата создания')
    last_upd = models.DateTimeField(auto_now=True, verbose_name='Дата последнего изменения', **NULLABLE)

    def __str__(self):
        return f'{self.name}'

    class Meta:
        verbose_name = 'Товар'
        verbose_name_plural = 'Товары'

catalog/views.py
from django.shortcuts import render
from catalog.models import Product


def home(request):
    product_list = Product.objects.all()
    context = {
        'object_list': product_list,
        'title': 'Главная'
    }
    return render(request, 'catalog/home.html', context)


def contacts(request, id):
    product = Product.objects.get(pk=id)
    context = {
        'object': product,
        'title': 'Детали'
    }
    return render(request, 'catalog/contacts.html', context)

catalog/templates/catalog/base.html
{% load static %}
{% load my_tags %}

<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{{ title }}</title>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
</head>
<body>
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
    <h5 class="my-0 mr-md-auto font-weight-normal">Skystore</h5>
    <nav class="ms-5">

        <a class="p-2 btn btn-outline-primary" href="{% url 'catalog:list' %}">Главная</a>
    </nav>
</div>

{% block content %}
{% endblock %}

<footer class="pt-4 my-md-5 pt-md-5 border-top">
        <div class="container">
            <p>&copy; {%  now 'Y' %}</p>
        </div>
</footer>
</div>

<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
</body>
</html>

catalog/templates/catalog/contacts.html
{% extends 'catalog/base.html' %}
{% load my_tags %}

{% block content %}

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">{{ object.name }}</h1>
</div>
<div class="container">
    <div class="row text-start">
        <div class="col-lg-9 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-body">
                    <table class="table table-striped">
                        <tr>
                            <td class="w-25">Описание</td>
                            <td>{{ object.description|slice:"100"}}</td>
                        </tr>
                        <tr>
                            <td class="w-25">Стоимость</td>
                            <td>{{ object.price }}
                        <tr>
                    </table>
                </div>

        </div>
{% endblock %}

catalog/templates/catalog/home.html
{% extends 'catalog/base.html' %}
{% load my_tags %}
{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Skystore</h1>
    <p class="lead">Список товаров</p>
</div>

<div class="container">
    <div class="row text-center">
        {% for object in object_list %}
        <div class="col-3">
            <div class="card mb-4 box-shadow">
                <img class="card-img-top"
                     src="{{ object.preview|my_media }}"
                     alt="Card image cap">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">{{ object }}</h4>
                </div>
                <div class="card-body">
                    <p class="card-title pricing-card-title">Стоимость {{ object.price }}</p>
                    <p>{{ object.description|slice:"100" }}</p>
                    <!--button type="button"  class="btn btn-lg btn-block btn-outline-primary">Подробнее</button-->
                    <a href="{% url 'catalog:details' object.id %}" type="button"  class="btn btn-lg btn-block btn-outline-primary">Подробнее</a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
{% endblock %}
</div>